title: Entropy as fuel for change.
author: Jon Choi
email: hello@jonchoi.com
url: "https://jonchoi.com"
description: > # this means to ignore newlines until "twitter_username:"
  I write stuff here.

# social links
twitter_username: jon_choi_
github_username: jonchoi
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jonathan-choi
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

disqus:
  shortname: jonchoi

# for testing future posts    
future: true

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

google_analytics: UA-85172652-2

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
